# -*- coding: utf-8 -*-
"""S1_R3 - AT1_LOPAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vguU_dmvWK8wmJgCf47eFFvx_otG3mXH

# **EXERCÍCIO 1:**

## **Calculadora de IMC**

O programa solicita que o usuário forneça suas informações a partir das funções de input() e, com a fórmula do IMC (peso dividido pela altura ao quadrado), consegue avaliar a sua classificação de peso por meio de vários if e elif's. Para fins estéticos, foi adicionado ao código cores no terminal (salvas em variáveis para facilitar o código). Também foi colocado a função sleep() para o programa simular um tempo de cálculo (embora ele calcule tudo instantaneamente). Também há alguns pequenos "easter eggs" de curiosidades sobre o homem mais pesado e o mais leve da história.
"""

from time import sleep

# ===================================================================
# CORES:

vermelho = "\033[0;31m"
verde = "\033[0;32m"
amarelo = "\033[0;33m"

# ====================================================================

print("Bem-vindo à calculadora de IMC. Porfavor, insira seus dados:")
altura = float(input("Digite sua altura em metros: "))
peso = float(input("Digite seu peso em kg: "))
imc = (peso/(altura*altura))
print('='*80)
print("Calculando...")
print('='*80)
sleep(2)
print("Seu IMC é de: {:.2f}".format(imc))

if imc < 6.92:
  print(f"{vermelho}Você provavelmente forneceu informações incorretas, visto que o homem mais leve da história (Isaac W. Sprague) tinha um IMC de 6.90")
elif imc > 6.92 and imc < 18.5:
  print(f"{amarelo}Sua classificação é de: Baixo peso")
elif imc > 18.5 and imc < 24.9:
  print(f"{verde}Sua classificação é de: Peso normal/ideal")
elif imc > 25 and imc < 29.9:
  print(f"{vermelho}Sua classificação é de: Sobrepeso")
elif imc > 30 and imc < 34.9:
  print(f"{vermelho}Sua classificação é de: Obesidade Grau I")
elif imc > 35 and imc < 39.9:
  print(f"{vermelho}Sua classificação é de: Obesidade Grau II")
elif imc > 40 and imc < 185.83:
  print(f"{vermelho}Sua classificação é de: Obesidade Grau III (Mórbida)")
elif imc > 185.84:
  print(f"{vermelho}Você provavelmente forneceu informações incorretas, visto que o homem mais pesado da história (Jon Brower Minnoch) tinha um IMC de 185.84")
else:
  print(f"{vermelho}Ocorreu um erro.")

"""# **EXERCÍCIO 2**

## **Cumprimentando pelo primeiro nome**

Esse simples programa solicita que o usuário informe seu nome e então realiza algumas funções para poder cumprimentar ele pelo primeiro nome. Primeiro, é removido espaços desnecessários com a função strip(), que remove espaços antes do primeiro caractere e depois do último caractere. Depois, a função title(), que faz com que a primeira letra do nome seja maiúscula. Por fim, a função split(), que separa o nome em diferentes "espaços" com base nos espaços (separando os nomes dos sobrenomes).
Por fim, "printamos" seu nome com uma cor no terminal e chamamos o primeiro nome dele (na posição 0).
"""

nome = input("Digite seu nome completo: ")
nome = nome.strip().title().split(' ')
print(f"\033[1;34mOlá, {nome[0]}.")

"""# **EXERCÍCIO 3**

## **Extraindo o domínio de um e-mail**

Com esse código, pedimos o email do usuário por um input, depois usamos duas funções que vão garantir a extração somente do endereço do e-mail provido pelo usuário. O strip() remove espaços desnecessários, para evitar que eles apareçam no código depois, e então o split('@') separa a string em duas partes: O que vem antes do @ e o que vem depois do @.
Por fim, "printamos" com uma cor no terminal tudo que vier depois do @, que geralmente é o domínio do e-mail.
"""

email = input("Digite seu e-mail: ")
email = email.strip()
email = email.split('@')
print(f"\033[1;32m O domínio do seu e-mail é\033[1;34m @{email[1]}")

"""# **EXERCÍCIO 4**

## **Loja de Tintas**

Para esse código, levamos em consideração os números de uma loja de tintas, que diz que:

- 1 Litro de tinta pinta 3m²;
- Cada lata contém 18 Litros;
- Cada lata custa R$80,00;

Considerando esses valores, o programa consegue calcular todos os custos baseado na quantidade de metros² que o usuário deseja pintar. Primeiro, solicitamos esse valor pelo input. Depois, calculamos a quantidade de litros necessários usando a fórmula metros / 3.

Depois, calculamos a quantiade de latas necessárias, aproximando seu valor para cima (isso porque ninguém compra, por exemplo, 2.3 latas de tinta). Para isso, usamos a função ceil, da biblioteca math, que faz exatamente isso. Então usamos a fórmula litros/18 e a função ceil aproxima ele para cima.

Depois, para calcular o preço, multiplicamos a quantidade de latas pelo seu valor, que no caso são 80 reais.

Por fim, mostramos os resultados por meio de um print, apresentando os valores e aproximando eles em 2 casas decimais.
"""

from math import ceil
metros = float(input("Digite quantos metros quadrados você deseja pintar: "))
litros =  metros / 3
latas = ceil(litros/18)
preco = latas * 80
print(f"Para você pintar {metros:.2f}m², você precisará comprar {latas} latas, e isso custará R${preco:.2f}")
# print(f"Especificamente seriam necessárias {litros/18} latas")

"""# **EXERCÍCIO 5**

## **Calculadora de Salário Líquido**

Esse programa realiza uma sequência de etapas para calcular o salário bruto, impostos pagos e salário líquido de um usuário. Ele faz isso na seguinte ordem:

1. Ele pede o valor em reais de quanto o usuário recebe por hora trabalhada.
2. Então, ele pede a quantidade de horas que o usuário trabalhou no mês.
3. Ele calcula o salário bruto multiplicando os dois valores anteriores.

4. Ele calcula quanto o usuário pagou de imposto de renda com a fórmula (Salário Bruto × 11) ÷ 100
5. Depois, calcula quanto o usuário pagou de INSS com a fórmula (Salário Bruto × 8) ÷ 100
6. Então, calcula quanto o usuário pagou ao Sindicato com a fórmula (Salário Bruto × 5) ÷ 100

7. Depois disso, ele calcula o salário líquido ao pegar o valor do salário bruto e subtrair os valores dos 3 impostos.

8. Por fim, mostra todos os resultados com um print formatado.
"""

salario = float(input('Digite quanto você recebe, em R$, por horas trabalhadas: '))
horas = int(input('Digite quantas horas você trabalhou nesse mês: '))

salario_bruto = salario * horas

imposto_de_renda = (salario_bruto * 11) / 100
inss = (salario_bruto * 8) / 100
sindicato = (salario_bruto * 5) / 100

salario_liquido = salario_bruto - imposto_de_renda - inss - sindicato

print('=' * 50)
print('Calculando seu salário...')
print('=' * 50)

print(f'Você recebeu um salário bruto de R${salario_bruto:.2f}. Porém, teve que pagar R${imposto_de_renda:.2f} de imposto de renda, R${inss:.2f} de INSS e R${sindicato:.2f} para o Sindicato. Portanto, seu salário líquido foi de R${salario_liquido:.2f}')

"""# **EXERCÍCIO 6**

## **Verificando se um ano é ou não bissexto**

Esse código verifica se um ano é ou não um ano bissexto a partir de uma condicional, que verifica se:

- Tal ano é múltiplo de 4
- Mas não é múltiplo de 100
- Porém, se for múltiplo de 100, se é múltiplo de 400

Se o ano que o usuário pediu para ser verificado atingir as 3 condições, então ele é um ano bissexto.
O código verifica também se o ano já passou ou se é um ano que ainda está no futuro. Se já passou, ele diz se o ano **"foi"** ou não bissexto. Se o ano ainda está no futuro, ele diz se o ano **"será"** ou não bissexto. Ele faz isso por uma condição aninhada a condição que verifica se o ano é bissexto ou não, vendo se tal ano é maior ou não que 2026.

Obviamente, se o ano não estiver dentro das condições de um ano bissexto, o else entra em ação e diz que o ano não foi/será bissexto.

Podemos descobrir se um número é múltiplo do outro por n¹ % n² == 0. Ou seja, se o resto da divisão entre n¹ e n² é zero. Se for zero, então são múltiplos.
"""

ano = int(input('Digite o ano que você quer verificar: '))

if ano % 4 == 0 and not ano % 100 == 0 or ano % 400 == 0:
  if ano > 2026:
    print(f'\033[1;32mSim, {ano} será um ano bissexto.')
  else:
    print(f'\033[1;32mSim, {ano} foi um ano bissexto.')
else:
  if ano > 2026:
    print(f'\033[1;31mNão, {ano} não será um ano bissexto')
  else:
    print(f'\033[1;31mNão, {ano} não foi um ano bissexto')

"""# **EXERCÍCIO 7**

## **Troca de Valores**

Há duas formas de realizar a troca de valores de variáveis em Python:
- Utilizando uma variável temporária;
- Utilizando uma tupla temporária;

Com uma variável temporária, bastaria colocar o valor de A em C (Sendo C a temporária), colocar o valor de B em A e o valor de C em B.

Porém, aqui, utilizamos o método alternativo e mais simples de troca de valores. Assim, o código funciona da seguinte forma:

1. O usuário dá os valores de A e B
2. O programa troca os valores de A e B usando uma tupla temporária.
3. O programa mostra os valores, agora trocados.

Basicamente, o lado direito é uma tupla temporária, que está guardando os valores b e a. Vamos tomar como exemplo que A = Olá e B = Mundo.
Então, ele cria uma tupla temporário que guarda os valores já invertidos, sendo Mundo, Olá. Então, ele atribui os valores das tuplas às variáveis a,b nessa respectiva ordem. Assim, ele dá que a = Mundo e b = Olá.

### Com variável temporária:

Também é possível realizar a troca de valores usando apenas uma terceira variável temporária.
"""

# Importando a função sleep da biblioteca time para fazer um efeito de "execução" do código para o resultado não aparecer imediatamente.
from time import sleep

a = input('Digite o valor da variável A: ')
b = input('Digite o valor da variável B: ')
print('Recapitulando:')
print(f'\033[1;31mO valor de A é {a}\033[m')
print(f'\033[1;32mO valor de B é {b}\033[m')

sleep(1)

print('\033[mTrocando valores...')

sleep(2)

a,b = b,a

print('\033[mPronto, valores trocados!')
print(f'\033[1;32mAgora, o valor de A é {a}\033[m')
print(f'\033[1;31mE o valor de B é {b}\033[m')

# Segundo Método (Terceira/Variável Temporária)
a = input('Digite o valor da variável A: ')
b = input('Digite o valor da variável B: ')

# Trocando os valores:

c = a
a = b
b = c

print(f'O valor de A agora é {a}.')
print(f'O valor de B agora é {b}.')

"""# **EXERCÍCIO 8**

## **Ímpar ou Par**

Esse código verifica se um número, solicitado ao usuário, é ímpar ou par.

Ele faz isso verificando se o número é múltiplo de 2. Se for múltiplo de dois, então é par. Se não for múltiplo de dois, então é ímpar.
"""

numero = int(input('Digite qual número você quer verificar: '))
if numero % 2 == 0:
  print(f'\033[1;32m{numero} é um número par.')
else:
  print(f'\033[1;31m{numero} é um número ímpar.')

"""# **EXERCÍCIO 9**
## **Organizando Valores em Ordem Crescente**

Com esse código, o usuário digita três números. Então, por meio de condições, verificamos todas as seis possíveis situações onde um deles é maior que o outro e mostramos eles por meio do print.

Também há uma segunda versão menor, porém que não usaria if, elif e else.
Essa segunda versão usa uma lista e a função sorted(), que automaticamente coloca ela em ordem crescente.
"""

n1 = int(input('Digite o valor do primeiro número: '))
n2 = int(input('Digite o valor do segundo número: '))
n3 = int(input('Digite o valor do terceiro número: '))
if n1 <= n2 and n2 <= n3:
    print(n1, n2, n3)
elif n1 <= n3 and n3 <= n2:
    print(n1, n3, n2)
elif n2 <= n1 and n1 <= n3:
    print(n2, n1, n3)
elif n2 <= n3 and n3 <= n1:
    print(n2, n3, n1)
elif n3 <= n1 and n1 <= n2:
    print(n3, n1, n2)
else:
    print(n3, n2, n1)

# Método Alternativo:
n1 = int(input('Digite o valor do primeiro número: '))
n2 = int(input('Digite o valor do segundo número: '))
n3 = int(input('Digite o valor do terceiro número: '))
ordem = [n1,n2,n3]
ordem = sorted(ordem)
print(*ordem)
